# GoReleaser configuration for did CLI
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: did
    main: .
    binary: did
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: did-archive
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  abbrev: 7
  format: "- [`{{ .SHA }}`](https://github.com/xolan/did/commit/{{ .SHA }}) {{ .Message }}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: xolan
    name: did
  draft: false
  prerelease: auto
  header: |
    ## did {{ .Version }}

    A CLI tool for time tracking. Log work activities with durations and view entries by time period.

    ### Installation

    **Download binary:**
    Download the appropriate archive for your platform below and extract the `did` binary.

    **Go install:**
    ```bash
    go install github.com/xolan/did@{{ .Tag }}
    ```

    ### Verifying Downloads

    Checksums are provided in `checksums.txt`. Verify your download:
    ```bash
    sha256sum -c checksums.txt --ignore-missing
    ```
