# GoReleaser configuration for did CLI
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: did
    main: .
    binary: did
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: did-archive
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  abbrev: 7
  format: "- [`{{ .SHA }}`](https://github.com/xolan/did/commit/{{ .SHA }}) {{ .Message }}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: did
    repository:
      owner: xolan
      name: homebrew-tap
    # Skip auto-push - requires PAT with write access to homebrew-tap
    # Update homebrew-tap manually or set up HOMEBREW_TAP_TOKEN secret
    skip_upload: true
    description: "A simple CLI tool for tracking time spent on tasks"
    homepage: "https://github.com/xolan/did"
    license: "MIT"
    install: |
      bin.install "did"

      # Generate and install shell completions
      output = Utils.safe_popen_read("#{bin}/did", "completion", "bash")
      (bash_completion/"did").write output

      output = Utils.safe_popen_read("#{bin}/did", "completion", "zsh")
      (zsh_completion/"_did").write output

      output = Utils.safe_popen_read("#{bin}/did", "completion", "fish")
      (fish_completion/"did.fish").write output
    test: |
      system "#{bin}/did", "--version"

release:
  github:
    owner: xolan
    name: did
  draft: false
  prerelease: auto
  header: |
    ## did {{ .Version }}

    A CLI tool for time tracking. Log work activities with durations and view entries by time period.

    ### Installation

    **Download binary:**
    Download the appropriate archive for your platform below and extract the `did` binary.

    **Go install:**
    ```bash
    go install github.com/xolan/did@{{ .Tag }}
    ```

    ### Verifying Downloads

    Checksums are provided in `checksums.txt`. Verify your download:
    ```bash
    sha256sum -c checksums.txt --ignore-missing
    ```
